### ISSUE TITLE
接口调用时加载字体图片报错

### ISSUE THREAD

**Issue by Sarahtorekryo** [ShannonAI/ChineseBert#16]
作者您好，感谢您的工作！请问我在依照quick tour中的实例调用接口时产生报错：ValueError: cannot reshape array of size 3555312 into shape (23236,24,24)，问题来自np.load(np_file).astype(np.float32) for np_file in font_npy_files，可以帮忙看看是什么原因吗？（是字体npy文件下载的有问题吗，重新下载了几遍都未解决，各依赖包的版本也都是完全按照requirement.txt中配置的）再次感谢您的工作和帮助~

**Comment by Smile-shirley** [comment]
您好，这个字体的图片从哪里下载？还有文字转拼音的

**Comment by Sarahtorekryo** [comment]
> 您好，这个字体的图片从哪里下载？还有文字转拼音的

可以看戏readme的Download部分，表格Model Hub一列下面蓝色的链接点进去

**Comment by Smile-shirley** [comment]
点进去了，但是没看到，能具体说下？

**Comment by Smile-shirley** [comment]
![image](https://user-images.githubusercontent.com/36403924/127865370-cf39d2a5-d48f-4485-bfa6-743ce0c6f7a7.png)

**Comment by Smile-shirley** [comment]
配置是上图？

**Comment by Sarahtorekryo** [comment]
> 配置是上图？
![image](https://user-images.githubusercontent.com/68192840/127871331-3f0bd06c-d9ca-4d14-925c-5d3a9928e16a.png)

**Comment by zijunsun** [comment]
可否提供下错误的完整截图？

**Comment by Sarahtorekryo** [comment]
> 可否提供下错误的完整截图？

感谢您的回复！错误如下图：
![8271c32090ed40534c925c2c123305e](https://user-images.githubusercontent.com/68192840/127874696-b6188e15-0f6c-4d85-915d-f71446c748d0.png)

**Comment by zijunsun** [comment]
我发现你这个array of size跟之前写的不一样了啊，看起来一直在变？

**Comment by Sarahtorekryo** [comment]
> 我发现你这个array of size跟之前写的不一样了啊，看起来一直在变？
好像真的是...不知道什么原因，检查了下下载的文件大小都与网站上一致，我下载的npy文件点开如图：
![image](https://user-images.githubusercontent.com/68192840/127875401-cca09dbc-2d9f-4524-adaf-d8d9fc5346be.png)

**Comment by zijunsun** [comment]
.npy文件是不能直接打开的，你可以直接load然后在程序里看数字

**Comment by zijunsun** [comment]
你可以试下，先单独load各个文件，然后看看每种字体，shape是不是一样的大小？

**Comment by Sarahtorekryo** [comment]
> 你可以试下，先单独load各个文件，然后看看每种字体，shape是不是一样的大小？
单独load好像还是下载的字体文件有问题，直接load不了（如图）
![image](https://user-images.githubusercontent.com/68192840/127876608-a7423565-6649-475e-b1d9-ebc14ea2a91c.png)

**Comment by zijunsun** [comment]
其他的都是可以的吗，就这个方正古隶的shape有问题？

**Comment by Sarahtorekryo** [comment]
> 其他的都是可以的吗，就这个方正古隶的shape有问题？

试了一下，都不能load，不同size的array of size不一样

**Comment by Sarahtorekryo** [comment]
***@***.***，万分感谢！想要引用您的工作输出的向量表示～



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月2日(周一) 晚上10:26
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ShannonAI/ChineseBert] 接口调用时加载字体图片报错 (#16)




 
其他的都是可以的吗，就这个方正古隶的shape有问题？

**Comment by zijunsun** [comment]
![image](https://user-images.githubusercontent.com/20966464/127879724-431f831c-d7d7-4032-a79e-db28f1858798.png)
我下载了下，运行之后，正常应该如图所示，你检查下你下载的文件吧，看是不是没下全，字体文件大小应该是101M左右

**Comment by Sarahtorekryo** [comment]
> ![image](https://user-images.githubusercontent.com/20966464/127879724-431f831c-d7d7-4032-a79e-db28f1858798.png)
> 我下载了下，运行之后，正常应该如图所示，你检查下你下载的文件吧，看是不是没下全，字体文件大小应该是101M左右

好的好的👌我再试下，辛苦您了，感谢您耐心的回复🌹
