### ISSUE TITLE
请问大佬总是出现这种错误怎么办，不知道怎么改

### ISSUE THREAD

**Issue by tiexueYL** [ShannonAI/ChineseBert#17]
(yl) D:\ChineseBert-main\tasks\THUCNew>python THUCNews_trainer.py --bert_path ./111/ --data_dir ./cnews/ --save_path ./222/ --max_epoch=5 --lr=2e-5 --batch_size=8 --gpus=0
Some weights of the model checkpoint at ./111/ were not used when initializing GlyceBertForSequenceClassification: ['cls.predictions.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.decoder.weight', 'cls.predictions.decoder.bias']
- This IS expected if you are initializing GlyceBertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPretraining model).
- This IS NOT expected if you are initializing GlyceBertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of GlyceBertForSequenceClassification were not initialized from the model checkpoint at ./111/ and are newly initialized: ['classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Traceback (most recent call last):
  File "THUCNews_trainer.py", line 229, in <module>
    main()
  File "THUCNews_trainer.py", line 193, in main
    model = ChnSentiClassificationTask(args)
  File "THUCNews_trainer.py", line 51, in __init__
    self.model = GlyceBertForSequenceClassification.from_pretrained(self.bert_dir)
  File "d:\ProgramData\Anaconda3\envs\yl\lib\site-packages\transformers\modeling_utils.py", line 1071, in from_pretrained
    model.__class__.__name__, "\n\t".join(error_msgs)
RuntimeError: Error(s) in loading state_dict for GlyceBertForSequenceClassification:
        size mismatch for bert.embeddings.glyph_embeddings.embedding.weight: copying a param with shape torch.Size([23236, 1728]) from checkpoint, the shape in current model is torch.Size([23236, 1152]).

**Comment by icestarsss** [comment]
您是如何解决这个问题的？我遇到了相同情况

**Comment by Richar-Du** [comment]
请问是如何解决的呢？
