### ISSUE TITLE
CUDA error: out of memory，显存需要多大？

### ISSUE THREAD

**Issue by zpyzl** [ShannonAI/ChineseBert#31]
large模型训练ChnSetiCorp，batch size设置为1，两个GPU ,每个11G显存，仍然报显存不够

**Comment by xiaoya-li** [comment]
您好，<br>
我们在V100,3090和TITAN Xp的GPU机器上, 使用ChnSetiCorp finetune ChineseBERT-Large，测试得到实验占用的GPU显存如下：<br>
当batch-size=1，precision=32时 
- TITAN Xp -> 10167MiB
- V100 -> 10706MiB 
- 3090 -> 11203MiB

您可以考虑将` --max_length`设置小一点, 这样应该就可以在11G显存的机器上跑起来。

**Comment by zpyzl** [comment]
好的，多谢
