### ISSUE TITLE
OSError: Failed to interpret file

### ISSUE THREAD

**Issue by zhunipingan** [ShannonAI/ChineseBert#32]
hi，
    I meet this error. OSError: Failed to interpret file 'chineseBert20210929/datasets/ChineseBERT-base/config/._STXINGKA.TTF24.npy' as a pickle. Do you know how to solve it. thanks.

**Comment by loopback00** [comment]
It's a pity that I just saw this problem now. The files starting with ._ are generated additionally when the Windows system is decompressed. Just delete all the files starting with ._  .
