### ISSUE TITLE
请教readme里面的那个示例的一个问题

### ISSUE THREAD

**Issue by drzqb** [ShannonAI/ChineseBert#5]
刚开始用pytorch的新手，就是readme里面的那个示例“我喜欢猫”，多次调用 chinese_bert.forward输出的结果由于模型里面有dropout不是应该不同吗，为什么我多次调用输出的结果总是一样的呢？

**Comment by zijunsun** [comment]
这个每次的输出肯定是一样的，因为在inference阶段，参数会被固定住。

**Comment by drzqb** [comment]
谢谢，在from_pretrained找到model.eval()了。
